---
title: ""
description: |
favicons: ["images/favicon.ico"]
theme: themes.css
--- 
<center>

## Veelgestelde vragen

</center>

We kunnen ons natuurlijk voorstellen dat je vragen hebt over de studie, daarom hebben wij de meest voorkomende vragen voor u op een rijtje gezet.

<b>Kan mijn kind ook als individu mee doen, en niet als klas?</b>
Ja, dat kan. U kunt contact opnemen door ons een e-mail te sturen, hier kunt u aangeven dat uw kind als individu mee wilt doen. We zullen u vervolgens alle nodige informatie sturen over het individueel meedoen met de studie. 

<b>Als ik niet in Nijmegen woon, kan mijn klas/mijn kind dan ook meedoen?</b>
Jazeker! Voor de gedragdsstudie komen de onderzoekers zelf naar de doorgegeven locatie, dus daar zal het wonen in Nijmegen geen probleem zijn. Voor het MRI deel van is het nodig om naar het Donders instituut in Nijmegen te komen. De reiskosten voor deze reis zullen vergoed worden. 

<b>Wat houdt het geven van toestemming voor het CODEC project  in?</b>
Alle informatie over het toezeggen van toestemming voor het meedoen aan de CODEC studie is te vinden in de informatiebrieven die u ontvangt voordat uw kind mee doet in het onderzoek. 

<b>Mijn contactgegevens zijn gewijzigd, wat nu?</b>
Als u contactgegevens zijn gewijzigd kunt u een mailtje sturen naar: codecstudies.cns@radboudumc.nl

<b>Kan ik mijn toestemming intrekken?</b>
Toestemming voor het onderzoek kan altijd ingetrokken worden.  Wanneer uw kind 12 wordt heeft hij/zij ook zelf de mogelijkheid om zijn toestemming in te trekken: uw kind blijft immers eigenaar van zijn gegevens. Dat kan
door contact op te nemen met privacy@ru.nl of gegevensbescherming@radboudumc.nl en te verwijzen naar de CODEC studie en Rogier Kievit. In het geval van zo’n verzoek zullen wij alle redelijke maatregelen nemen om de data van uw kind niet in toekomstige analyses te gebruiken.

<b> Ik heb een vraag over de privacy of de gegevensberscherming </b>
Voor vragen over gegevensbescherming en privacy kunt u contact opnemen met de Functionaris Gegevensbescherming van het RadboudUMC op gegevensbescherming@radboudumc.nl.

<b>Waar kan ik de wetenschappelijke publicaties over het CODEC onderzoek vinden?</b>
De toekomstige wetenschappelijke publicaties over het CODEC onderzoek, zijn te vinden op [deze](onderzoek.html) pagina. 

<b>Wie voert het onderzoek uit </b>
Het onderzoek wordt uitgevoert door Rogier, Ilse, Jordy, Emma, Sophie en Jesse. Wij zijn onderdeel van het CODEC team, gevestigd bij het [Lifespan Cognitive Dynamics Lab](https://lifespancognitivedynamics.com) aan het [Donders Instituut](https://www.ru.nl/donders/). Meer informatie over ons team is te vinden op [deze](team.html) pagina. 


<b>Verdere vragen?</b>
Heeft u vragen die niet beantwoord worden op de site? Dan kunt u mailen naar:
<strong>codecstudies.cns@radboudumc.nl
</strong>
